from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://www.facebook.com/')
email = driver.find_element_by_xpath('//*[@id="email"]')
email.send_keys("746095525")
password = driver.find_element_by_xpath('//*[@id="pass"]')
password.send_keys('myhomesweethome')
login = driver.find_element_by_xpath('//*[@id="loginbutton"]')
login.click()
likebtn = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[1]/div/div[2]/div[2]/div[1]/div[2]/div/div[6]/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[2]/form/div/div[2]/div/div[2]/div/span[1]')
likebtn.click()